apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: default
spec:
  interval: 30m
  targetNamespace: external-secrets  # 3. Explicitly forces Helm installation target
  install:
    createNamespace: true
  chart:
    spec:
      chart: external-secrets
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: default